### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by tarkus2000ua** [tarkus2000ua/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by t-collaborator** [comment]
https://www.facebook.com/profile.php?id=100004808958030
ryuwins@gmail.com
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/
